categories:
  - title: 'Features'
    label: 'feature'
  - title: 'Enhancement'
    label: 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Release Notes

  $CHANGES

  $CONTRIBUTORS
