version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - /releases\/*/
skip_non_tags: true
skip_branch_with_pr: true
build_script:
- ps: "$env:resourceRoot\\build\\build_appveyor.ps1"
test_script:
- ps: >-
    Install-Module Pester -Force -Scope CurrentUser

    Invoke-Pester -EnableExit
deploy: off
on_success:
- ps: $newManifestTest = Test-ModuleManifest -Path "$env:sourceRoot\$env:moduleName.psd1"
on_finish:
- ps: >-
    if ($newManifestTest) {
        #Publish-Module -Path "$env:sourceRoot" -NuGetApiKey "$env:galleryPublishingKey"
    }