version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - /development/
skip_non_tags: true
build_script:
- ps: "# This file in it self is not used but only a template.\n# Actual code that will be executed lives in appveyor.yml\n\nNew-Module -Name \"$env:moduleName\" -ScriptBlock {\n    $modulePath = \"$env:moduleRoot\\$env:moduleName.psm1\"\n    $privScripts = Get-ChildItem -Path \"$env:sourceRoot\\private\" -Filter \"*.ps1\" -Recurse\n    $pubScripts = Get-ChildItem -Path \"$env:sourceRoot\\public\" -Filter \"*.ps1\" -Recurse\n    if (!(Test-Path -Path $modulePath)) {\n        $newModuleDir = New-Item -Path \"$env:resourceRoot\" -Name \"$env:moduleName\" -ItemType 'directory' -Force\n        $newModuleFile = New-Item -Path \"$env:moduleRoot\" -Name \"$env:moduleName.psm1\" -ItemType \"file\"\n    }\n    foreach ($privateScript in $privScripts) {\n        $scriptContent = Get-Content -Path \"$($privateScript.FullName)\" -Raw\n        if (Test-Path -Path $modulePath) {\n            Add-Content -Path $modulePath -Value $scriptContent\n        } else {\n            Write-Output \"Unable to find modulePath at $modulePath\" -ForegroundColor Red\n        }\n    }\n    foreach ($publicScript in $pubScripts) {\n        $scriptContent = Get-Content -Path \"$($publicScript.FullName)\" -Raw\n        if (Test-Path -Path $modulePath) {   \n            Add-Content -Path $modulePath -Value $scriptContent                     \n            Add-Content -Path $modulePath -Value \"Export-ModuleMember -Function $($publicScript.BaseName)\"\n        } else {\n            Write-Output \"Unable to find modulePath at $modulePath\" -ForegroundColor Red\n        }\n    }\n}\n$manifest = @{\n    Path              = \"$env:moduleRoot\\$env:moduleName.psd1\" \n    RootModule        = \"$env:moduleName.psm1\" \n    CompanyName       = \"$env:companyName\"\n    Author            = \"$env:moduleAuthor\"\n    ModuleVersion     = \"$env:APPVEYOR_BUILD_VERSION\"\n    HelpInfoUri       = \"$env:helpInfoUri\"\n    LicenseUri        = \"$env:licenseUri\"\n    ProjectUri        = \"$env:projectUri\"\n    Description       = 'Management Framework for Easit BPS and Easit GO'\n    PowerShellVersion = '5.1'\n    Copyright         = \"(c) 2020 $env:companyName. All rights reserved.\"\n}\nNew-ModuleManifest @manifest"
test_script:
- ps: >-
    Install-Module Pester -Force

    Invoke-Pester
on_finish:
- ps: >-
    "$manifestFile = Join-Path -Path \"$env:moduleRoot\" -ChildPath \"${env:moduleName}.psd1\""
    "Write-Host "$manifestFile""
    
    "Write-Host \"$env:moduleRoot\""
    
    "Write-Host \"$env:moduleName\""

    "if (Test-ModuleManifest -Path \"$manifestFile\") {Publish-Module -Path \"$env:moduleRoot\" -NuGetApiKey \"$env:galleryPublishingKey\"}"
