pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - /development/
skip_non_tags: true
test: off
on_success:
- ps: $newManifestTest = Test-ModuleManifest -Path "$env:sourceRoot\$env:moduleName.psd1"
on_finish:
- ps: >-
    if ($newManifestTest) {
            #Publish-Module -Path "$env:sourceRoot" -NuGetApiKey "$env:galleryPublishingKey"
        }
