name: Push and PR test

on:
  push:
    paths:
    - 'src/priv/*.ps1'
    - 'src/pub/*.ps1'
  pull_request:
    paths:
    - 'src/priv/*.ps1'
    - 'src/pub/*.ps1'

jobs:
  lint:
    name: Run PSSA
    runs-on: ubuntu-latest
    steps:
    - uses: devblackops/github-action-psscriptanalyzer@master

  test:
    name: Pester tests
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install Pester
      shell: pwsh
      run: Install-Module Pester -Force
    - name: Invoke Pester
      shell: pwsh
      run: Invoke-Pester -EnableExit
